### Create Users
POST http://{{host}}:{{port}}/api/users/create
content-type: application/json

{
  "id": "fastlane",
  "password": "fastlane"
}

### Get UserById
GET http://{{host}}:{{port}}/api/users/fastlane2

### Modify password
PUT http://{{host}}:{{port}}/api/users/fastlane
content-type: application/json

{
  "password": "newFastlane",
  "newPassword": "newFastlane1"
}

### Get Users
GET http://{{host}}:{{port}}/api/users/

### Delete User
DELETE http://{{host}}:{{port}}/api/users/fastlane
